'use strict';

// ── Estados de armazenamento (afeta a validade calculada) ────
const ETQ_ARMAZENAMENTO_DEFAULT = [
  { id: 'resfriado', nome: 'Resfriado',     icon: '❄️' },
  { id: 'congelado', nome: 'Congelado',     icon: '🧊' },
  { id: 'seco',      nome: 'Seco/Ambiente', icon: '📦' },
];

// ── Tabela de regras de validade (CVS/RDC — versionada, editável no Config) ──
// Fonte: RDC 216/2004 ANVISA (lei vigente em Curitiba/PR) + Portaria CVS 5/2013 (SP,
// referência técnica de mercado nacional, válida até 03/10/2026) + CVS 3/2026 (sucessora,
// vigente a partir de 04/10/2026). Ver memória do projeto pra detalhes e fontes.
// Cada categoria tem "variantes" por estado de armazenamento — nem toda categoria
// tem as 3 (ex: maionese não costuma congelar, secos não resfria/congela).
const ETIQUETAS_CATEGORIAS_DEFAULT = [
  { id: 'hortifruti_higienizado', nome: 'Hortifruti higienizado/cortado', variantes: {
      resfriado: { temp: '5°C',  dias: 3,  fonte: 'CVS 5/2013' },
      congelado: { temp: '-18°C',dias: 90, fonte: 'CVS 5/2013' },
  }},
  { id: 'carnes_aves_cruas', nome: 'Carnes e aves cruas', variantes: {
      resfriado: { temp: '4°C',  dias: 3,  fonte: 'CVS 5/2013' },
      congelado: { temp: '-18°C',dias: 90, fonte: 'CVS 5/2013' },
  }},
  { id: 'pescado_cru', nome: 'Pescado cru', variantes: {
      resfriado: { temp: '2°C',  dias: 3,  fonte: 'CVS 5/2013' },
      congelado: { temp: '-18°C',dias: 90, fonte: 'CVS 5/2013' },
  }},
  { id: 'laticinios', nome: 'Laticínios abertos', variantes: {
      resfriado: { temp: '7°C',  dias: 5,  fonte: 'CVS 5/2013' },
      congelado: { temp: '-18°C',dias: 90, fonte: 'CVS 5/2013' },
  }},
  { id: 'maionese_derivados', nome: 'Maionese e molhos frios', variantes: {
      resfriado: { temp: '4°C',  dias: 2,  fonte: 'CVS 5/2013' },
  }},
  { id: 'ovos', nome: 'Ovos', variantes: {
      resfriado: { temp: '10°C', dias: 7,  fonte: 'CVS 5/2013' },
  }},
  { id: 'preparado_geral', nome: 'Preparado/produzido (geral)', variantes: {
      resfriado: { temp: '4°C',  dias: 3,  fonte: 'RDC 216/2004 + CVS 5/2013' },
      congelado: { temp: '-18°C',dias: 90, fonte: 'CVS 5/2013' },
  }},
  { id: 'secos_graos', nome: 'Secos, grãos e temperos', variantes: {
      seco: { temp: 'ambiente', dias: 60, fonte: 'prática de mercado — conferir rótulo do fabricante' },
  }},
];

// ── Grupos de insumo (organização/filtro — mesma lógica das seções já usadas no app:
// HORTI, COZINHA>Proteínas/Laticínios/Secos, BEBIDAS, PRODUCAO) ──
const ETQ_GRUPOS_DEFAULT = [
  { id: 'hortifruti', nome: 'Hortifruti', icon: '🥬' },
  { id: 'carnes',     nome: 'Carnes',     icon: '🥩' },
  { id: 'frango',     nome: 'Frango',     icon: '🍗' },
  { id: 'pescados',   nome: 'Pescados',   icon: '🐟' },
  { id: 'laticinios', nome: 'Laticínios', icon: '🧀' },
  { id: 'secos',      nome: 'Secos e Grãos', icon: '🌾' },
  { id: 'bebidas',    nome: 'Bebidas',    icon: '🥤' },
  { id: 'producao',   nome: 'Itens Produzidos', icon: '🍲' },
  { id: 'outros',     nome: 'Outros',     icon: '📦' },
];

// ── Catálogo inicial de itens (derivado da planilha CUSTOS, filtrado — sem embalagens) ─
// origem 'custos' = veio da planilha mãe de CMV | 'cadastro_loja' = cadastrado por funcionário
// pendenteRevisao: true = categoria de validade atribuída automaticamente, sem alta confiança — revisar
// cat = categoria de validade (regra CVS/RDC) | grupo = tipo de insumo (organização/filtro)
const ETIQUETAS_CATALOGO_DEFAULT = [
  {id:"cs_alface_americana",nome:"Alface americana",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:18.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_mix_de_folhas",nome:"Mix de folhas",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:23.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_repolho_branco",nome:"Repolho branco",unidade:"un",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:2.77,origem:"custos",pendenteRevisao:false},
  {id:"cs_repolho_roxo",nome:"Repolho roxo",unidade:"un",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:11.32,origem:"custos",pendenteRevisao:false},
  {id:"cs_escarola",nome:"Escarola",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:27.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_manjericao",nome:"Manjericão",unidade:"mc",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:10.62,origem:"custos",pendenteRevisao:false},
  {id:"cs_couve",nome:"Couve",unidade:"mc",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:5.02,origem:"custos",pendenteRevisao:false},
  {id:"cs_aipim",nome:"Aipim",unidade:"KG",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:6.5,origem:"custos",pendenteRevisao:false},
  {id:"cs_cogumelos_paris",nome:"Cogumelos paris",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:34.5,origem:"custos",pendenteRevisao:false},
  {id:"cs_ovos",nome:"Ovos",unidade:"30 um",cat:"ovos",grupo:"hortifruti",preco:0.6,origem:"custos",pendenteRevisao:false},
  {id:"cs_edamame",nome:"Edamame",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:45.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_tomate_italiano",nome:"Tomate italiano",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:4.15,origem:"custos",pendenteRevisao:false},
  {id:"cs_tomate_cereja",nome:"Tomate cereja",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:12.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_berinjela",nome:"Berinjela",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:4.51,origem:"custos",pendenteRevisao:false},
  {id:"cs_abobrinha",nome:"Abobrinha",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:2.95,origem:"custos",pendenteRevisao:false},
  {id:"cs_limao",nome:"Limão",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:9.36,origem:"custos",pendenteRevisao:false},
  {id:"cs_alho",nome:"Alho",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:29.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_couve_flor",nome:"Couve flor",unidade:"un",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:8.1,origem:"custos",pendenteRevisao:false},
  {id:"cs_abobora",nome:"Abóbora",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:6.71,origem:"custos",pendenteRevisao:false},
  {id:"cs_cebola",nome:"Cebola",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:3.32,origem:"custos",pendenteRevisao:false},
  {id:"cs_cebola_roxa",nome:"Cebola Roxa",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:4.4,origem:"custos",pendenteRevisao:false},
  {id:"cs_pupunha_laminada",nome:"Pupunha laminada",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:24.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_pupunha_spaghetti",nome:"Pupunha spaghetti",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:24.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_cenoura",nome:"Cenoura",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:3.78,origem:"custos",pendenteRevisao:false},
  {id:"cs_pepino",nome:"Pepino",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:12.35,origem:"custos",pendenteRevisao:false},
  {id:"cs_batata_doce_palha",nome:"Batata Doce Palha",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:20.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_salsinha",nome:"Salsinha",unidade:"mc",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:1.78,origem:"custos",pendenteRevisao:false},
  {id:"cs_cebolinha",nome:"Cebolinha",unidade:"mc",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:1.18,origem:"custos",pendenteRevisao:false},
  {id:"cs_abacate",nome:"Abacate",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:11.82,origem:"custos",pendenteRevisao:false},
  {id:"cs_presunto_parma",nome:"PRESUNTO PARMA",unidade:"kg",cat:"carnes_aves_cruas",grupo:"carnes",preco:138.6,origem:"custos",pendenteRevisao:false},
  {id:"cs_bacon_em_cubos_de_pernil",nome:"BACON EM CUBOS DE PERNIL",unidade:"kg",cat:"carnes_aves_cruas",grupo:"carnes",preco:53.5,origem:"custos",pendenteRevisao:false},
  {id:"cs_bacon_manta_feijoada",nome:"BACON MANTA - FEIJOADA",unidade:"kg",cat:"carnes_aves_cruas",grupo:"carnes",preco:63.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_mignon_cubos_limpo",nome:"MIGNON CUBOS (LIMPO)",unidade:"kg",cat:"carnes_aves_cruas",grupo:"carnes",preco:79.9,origem:"custos",pendenteRevisao:false},
  {id:"cs_mignon_tiras_strogonoff",nome:"MIGNON TIRAS STROGONOFF",unidade:"kg",cat:"carnes_aves_cruas",grupo:"carnes",preco:79.9,origem:"custos",pendenteRevisao:false},
  {id:"cs_file_de_peito_de_frango",nome:"FILE DE PEITO DE FRANGO",unidade:"kg",cat:"carnes_aves_cruas",grupo:"frango",preco:18.53,origem:"custos",pendenteRevisao:false},
  {id:"cs_file_de_salmao_limpo_sem_pele",nome:"FILÉ DE SALMÃO LIMPO SEM PELE",unidade:"kg",cat:"pescado_cru",grupo:"pescados",preco:110.25,origem:"custos",pendenteRevisao:false},
  {id:"cs_carne_moida_primeira",nome:"CARNE MOÍDA PRIMEIRA",unidade:"kg",cat:"carnes_aves_cruas",grupo:"carnes",preco:33.75,origem:"custos",pendenteRevisao:false},
  {id:"cs_tilapia",nome:"TILAPIA",unidade:"kg",cat:"pescado_cru",grupo:"pescados",preco:45.63,origem:"custos",pendenteRevisao:false},
  {id:"cs_calabresa",nome:"CALABRESA",unidade:"kg",cat:"carnes_aves_cruas",grupo:"carnes",preco:24.2,origem:"custos",pendenteRevisao:false},
  {id:"cs_peito_de_peru",nome:"PEITO DE PERU",unidade:"kg",cat:"carnes_aves_cruas",grupo:"frango",preco:52.8,origem:"custos",pendenteRevisao:false},
  {id:"cs_creme_de_leite_zero_lactose",nome:"CREME DE LEITE ZERO LACTOSE",unidade:"KG",cat:"laticinios",grupo:"laticinios",preco:20.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_parmesao",nome:"PARMESÃO",unidade:"KG",cat:"laticinios",grupo:"laticinios",preco:45.9,origem:"custos",pendenteRevisao:false},
  {id:"cs_parmesao_12_meses_cura_zero_lactose",nome:"PARMESÃO 12 MESES CURA (ZERO LACTOSE)",unidade:"KG",cat:"laticinios",grupo:"laticinios",preco:95.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_mucarela_bufala",nome:"MUÇARELA BUFALA",unidade:"KG",cat:"laticinios",grupo:"laticinios",preco:58.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_iogurte_natural_zero_lactose",nome:"IOGURTE NATURAL ZERO LACTOSE",unidade:"KG",cat:"laticinios",grupo:"laticinios",preco:12.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_ricota",nome:"RICOTA",unidade:"KG",cat:"laticinios",grupo:"laticinios",preco:13.5,origem:"custos",pendenteRevisao:false},
  {id:"cs_leite_desnatado",nome:"LEITE DESNATADO",unidade:"litro",cat:"laticinios",grupo:"laticinios",preco:6.5,origem:"custos",pendenteRevisao:false},
  {id:"cs_mucarela",nome:"MUCARELA",unidade:"KG",cat:"laticinios",grupo:"laticinios",preco:34.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_manteiga",nome:"MANTEIGA",unidade:"KG",cat:"laticinios",grupo:"laticinios",preco:31.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_requeijao_light",nome:"REQUEIJAO LIGHT",unidade:"KG",cat:"laticinios",grupo:"laticinios",preco:31.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_leite_de_coco",nome:"Leite de coco",unidade:"litro",cat:"laticinios",grupo:"laticinios",preco:14.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_acucar_demerara",nome:"Açúcar demerara",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:5.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_tomate_seco",nome:"Tomate seco",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:35.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_maionese_helmanns_lisa_du_chef",nome:"Maionese (Helmanns/Lisa Du Chef)",unidade:"kg",cat:"maionese_derivados",grupo:"secos",preco:14.5,origem:"custos",pendenteRevisao:false},
  {id:"cs_mostarda_amarela_hemmer_heinz",nome:"Mostarda amarela (Hemmer, Heinz)",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:10.52,origem:"custos",pendenteRevisao:false},
  {id:"cs_azeite_de_oliva_acidez_max_0_5",nome:"Azeite de oliva (acidez max 0,5)",unidade:"litro",cat:"secos_graos",grupo:"secos",preco:18.6,origem:"custos",pendenteRevisao:false},
  {id:"cs_mel",nome:"Mel",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:20.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_ervas_finas",nome:"Ervas finas",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:30.3,origem:"custos",pendenteRevisao:false},
  {id:"cs_shoyu_light",nome:"Shoyu Light",unidade:"litro",cat:"secos_graos",grupo:"secos",preco:6.6,origem:"custos",pendenteRevisao:false},
  {id:"cs_tomate_pelado",nome:"Tomate pelado",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:9.28,origem:"custos",pendenteRevisao:false},
  {id:"cs_extrato_de_tomate",nome:"Extrato de tomate",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:8.97,origem:"custos",pendenteRevisao:false},
  {id:"cs_oleo_de_algodao",nome:"Oleo de Algodão",unidade:"litro",cat:"secos_graos",grupo:"secos",preco:9.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_conhaque",nome:"Conhaque",unidade:"litro",cat:"secos_graos",grupo:"secos",preco:20.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_arroz_integral",nome:"Arroz integral",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:7.5,origem:"custos",pendenteRevisao:false},
  {id:"cs_pao_integral",nome:"Pão integral",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:13.25,origem:"custos",pendenteRevisao:false},
  {id:"cs_pao_folha",nome:"Pão folha",unidade:"unidade",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:1.5,origem:"custos",pendenteRevisao:false},
  {id:"cs_balsamico",nome:"Balsâmico",unidade:"litro",cat:"preparado_geral",grupo:"producao",preco:17.34,origem:"custos",pendenteRevisao:true},
  {id:"cs_molho_ingles",nome:"Molho Ingles",unidade:"litro",cat:"maionese_derivados",grupo:"secos",preco:3.49,origem:"custos",pendenteRevisao:false},
  {id:"cs_feijao_preto_caldo_bom_urbano_pe_vermelho",nome:"Feijão Preto (Caldo bom, Urbano, Pé Vermelho)",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:8.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_farelo_de_aveia",nome:"Farelo de aveia",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:19.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_farinha_de_mandioca",nome:"Farinha de mandioca",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:3.79,origem:"custos",pendenteRevisao:false},
  {id:"cs_sal",nome:"Sal",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:1.15,origem:"custos",pendenteRevisao:false},
  {id:"cs_vinagre_vinho_tinto",nome:"Vinagre vinho tinto",unidade:"litro",cat:"secos_graos",grupo:"secos",preco:1.5,origem:"custos",pendenteRevisao:false},
  {id:"cs_chia",nome:"Chia",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:30.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_linhaca",nome:"Linhaça",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:17.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_nozes",nome:"Nozes",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:41.39,origem:"custos",pendenteRevisao:false},
  {id:"cs_farinha_de_linhaca",nome:"Farinha de linhaça",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:17.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_paprica_defumada",nome:"Paprica Defumada",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:9.06,origem:"custos",pendenteRevisao:false},
  {id:"cs_pimenta_do_reino",nome:"Pimenta do reino",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:18.5,origem:"custos",pendenteRevisao:false},
  {id:"cs_louro",nome:"Louro",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:40.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_amendoa_laminada",nome:"Amendoa laminada",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:69.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_semente_de_girassol_pepita",nome:"Semente de girassol (pepita)",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:15.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_amendoim_torrado",nome:"Amendoim torrado",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:23.2,origem:"custos",pendenteRevisao:false},
  {id:"cs_mix_de_gergelin_preto_e_branco",nome:"Mix de gergelin (preto e branco)",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:28.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_agua",nome:"Água",unidade:"litro",cat:"secos_graos",grupo:"secos",preco:0.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_trigo",nome:"Trigo",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:2.61,origem:"custos",pendenteRevisao:false},
  {id:"cs_oregano",nome:"Orégano",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:56.18,origem:"custos",pendenteRevisao:false},
  {id:"cs_mate",nome:"Mate",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:240.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_carne_posta_vermelha",nome:"Carne posta vermelha",unidade:"kg",cat:"carnes_aves_cruas",grupo:"carnes",preco:33.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_costelinha",nome:"Costelinha",unidade:"kg",cat:"carnes_aves_cruas",grupo:"carnes",preco:37.8,origem:"custos",pendenteRevisao:false},
  {id:"cs_lemon_pepper",nome:"Lemon pepper",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:21.75,origem:"custos",pendenteRevisao:false},
  {id:"cs_limao_siciliano",nome:"Limão siciliano",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:9.5,origem:"custos",pendenteRevisao:false},
  {id:"cs_paprica_doce",nome:"Páprica doce",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:17.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_cafe",nome:"Café",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:40.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_pepino_conserva",nome:"Pepino Conserva",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:17.06,origem:"custos",pendenteRevisao:false},
  {id:"cs_milho",nome:"Milho",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:13.53,origem:"custos",pendenteRevisao:false},
  {id:"cs_gorgonzola",nome:"Gorgonzola",unidade:"kg",cat:"laticinios",grupo:"laticinios",preco:65.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_brocolis",nome:"Brocolis",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:30.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_macarrao_parafuso_integral",nome:"Macarrão Parafuso Integral",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:8.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_molho_sakura",nome:"Molho Sakura",unidade:"litro",cat:"maionese_derivados",grupo:"secos",preco:40.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_noz_moscada",nome:"Noz Moscada",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:65.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_batata_branca",nome:"Batata branca",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:6.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_produtos_prontos_pre_preparo",nome:"PRODUTOS PRONTOS (pré preparo)",unidade:"un",cat:"preparado_geral",grupo:"producao",origem:"custos",pendenteRevisao:true},
  {id:"cs_pate_sanduiche_natural",nome:"Pate Sanduiche Natural",unidade:"kg",cat:"preparado_geral",grupo:"producao",preco:13.76,origem:"custos",pendenteRevisao:true},
  {id:"cs_molho_mostarda_e_mel",nome:"Molho mostarda e mel",unidade:"kg",cat:"maionese_derivados",grupo:"secos",preco:16.15,origem:"custos",pendenteRevisao:false},
  {id:"cs_molho_ranch",nome:"Molho ranch",unidade:"kg",cat:"maionese_derivados",grupo:"secos",preco:16.18,origem:"custos",pendenteRevisao:false},
  {id:"cs_italian_balsamico_mostarda_e_mel",nome:"Italian: balsâmico, mostarda e mel",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:17.31,origem:"custos",pendenteRevisao:false},
  {id:"cs_molho_golf",nome:"Molho Golf",unidade:"kg",cat:"maionese_derivados",grupo:"secos",preco:14.28,origem:"custos",pendenteRevisao:false},
  {id:"cs_molho_pomodoro",nome:"Molho pomodoro",unidade:"kg",cat:"maionese_derivados",grupo:"secos",preco:8.27,origem:"custos",pendenteRevisao:false},
  {id:"cs_molho_bolonhesa",nome:"Molho bolonhesa",unidade:"kg",cat:"maionese_derivados",grupo:"secos",preco:22.8,origem:"custos",pendenteRevisao:false},
  {id:"cs_creme_de_ricota",nome:"Creme de ricota",unidade:"kg",cat:"laticinios",grupo:"laticinios",preco:15.92,origem:"custos",pendenteRevisao:false},
  {id:"cs_legumes_salteados",nome:"Legumes salteados",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:0.83,origem:"custos",pendenteRevisao:false},
  {id:"cs_mignon_salteado",nome:"Mignon salteado",unidade:"kg",cat:"carnes_aves_cruas",grupo:"carnes",preco:84.69,origem:"custos",pendenteRevisao:false},
  {id:"cs_feijao_preto_cozido",nome:"Feijão preto cozido",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:4.5,origem:"custos",pendenteRevisao:false},
  {id:"cs_frango_grelhado",nome:"Frango grelhado",unidade:"kg",cat:"carnes_aves_cruas",grupo:"frango",preco:19.52,origem:"custos",pendenteRevisao:false},
  {id:"cs_tilapia_grelhada",nome:"Tilápia grelhada",unidade:"kg",cat:"pescado_cru",grupo:"pescados",preco:48.98,origem:"custos",pendenteRevisao:false},
  {id:"cs_farofa_de_cenoura_linhaca_e_chia",nome:"Farofa de cenoura, linhaça e chia",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:11.49,origem:"custos",pendenteRevisao:false},
  {id:"cs_arroz_integral_pronto",nome:"Arroz integral pronto",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:3.16,origem:"custos",pendenteRevisao:false},
  {id:"cs_mix_de_sementes_e_amendoas",nome:"Mix de sementes e amêndoas",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:42.5,origem:"custos",pendenteRevisao:false},
  {id:"cs_croutons_integrais",nome:"Croutons integrais",unidade:"kg",cat:"preparado_geral",grupo:"producao",preco:15.66,origem:"custos",pendenteRevisao:true},
  {id:"cs_chips_de_batata_doce",nome:"Chips de batata doce",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:20.0,origem:"custos",pendenteRevisao:false},
  {id:"cs_pesto_de_manjericao",nome:"Pesto de manjericão",unidade:"kg",cat:"maionese_derivados",grupo:"secos",preco:45.17,origem:"custos",pendenteRevisao:false},
  {id:"cs_abobrinha_assada",nome:"Abobrinha assada",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:3.52,origem:"custos",pendenteRevisao:false},
  {id:"cs_cogumelo_refogado",nome:"Cogumelo refogado",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:38.8,origem:"custos",pendenteRevisao:false},
  {id:"cs_feijoada",nome:"Feijoada",unidade:"kg",cat:"preparado_geral",grupo:"producao",preco:21.69,origem:"custos",pendenteRevisao:true},
  {id:"cs_frango_desfiado",nome:"Frango desfiado",unidade:"kg",cat:"carnes_aves_cruas",grupo:"frango",preco:21.12,origem:"custos",pendenteRevisao:false},
  {id:"cs_carne_desfiada",nome:"Carne desfiada",unidade:"kg",cat:"carnes_aves_cruas",grupo:"carnes",preco:41.21,origem:"custos",pendenteRevisao:false},
  {id:"cs_arroz_de_couve_flor",nome:"Arroz de couve flor",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:11.16,origem:"custos",pendenteRevisao:false},
  {id:"cs_tempero_all",nome:"Tempero all",unidade:"kg",cat:"secos_graos",grupo:"secos",preco:23.72,origem:"custos",pendenteRevisao:false},
  {id:"cs_couve_refogada",nome:"Couve refogada",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:5.75,origem:"custos",pendenteRevisao:false},
  {id:"cs_vinagrete_all",nome:"Vinagrete ALL",unidade:"kg",cat:"maionese_derivados",grupo:"secos",preco:3.86,origem:"custos",pendenteRevisao:false},
  {id:"cs_farofa_de_cebola",nome:"Farofa de cebola",unidade:"kg",cat:"hortifruti_higienizado",grupo:"hortifruti",preco:7.21,origem:"custos",pendenteRevisao:false},
  {id:"cs_guacamole",nome:"Guacamole",unidade:"kg",cat:"maionese_derivados",grupo:"secos",preco:8.31,origem:"custos",pendenteRevisao:false}
];
